version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:17.6.0-debian-12-r4
    container_name: taskly-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskly
    volumes:
      - postgres-data:/bitnami/postgresql
    ports:
      - "5432:5432"
    restart: unless-stopped

  taskly-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskly-app
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: taskly
      DATABASE_PORT: 5432
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  postgres-data:
